### ISSUE TITLE
Can't build and integrate the provider with Terraform

### ISSUE THREAD

**Issue by arun2arunraj** [avinetworks/terraform-provider-avi#54]
hi Team,

    I am trying to create Virtual Service in AVI through this provider. But, I couldn't even integrate this provider with Terraform. Build itself failed, it seems.

     Steps that done.
     
      1 ) Installed & configured GO and GOPATH
      2 ) took a clone of the provider in the local ( git clone https://github.com/avinetowrks/terraform-provider-avi.git)
      3 ) renamed the hashicorp to avinetworks ( mv src/github.com/hashicorp src/github.com/avinetworks )
      4 ) took a clone of the sdk inside the avinetworks folder ( git clone https://github.com/avinetworks/sdk.git
      5 ) make build

Below was the statement that I have received.

ADS1223412ddsCDD:terraform-provider-avi arunraj_r$ make build
==> Checking that code complies with gofmt requirements...
go install

     Due to the above message, Not sure whether it is installed or not.
     
       6 ) make test

ADS1223412ddsCDD:terraform-provider-avi arunraj_r$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/avinetworks/terraform-provider-avi github.com/avinetworks/terraform-provider-avi/avi
?   	github.com/avinetworks/terraform-provider-avi	[no test files]
# github.com/avinetworks/terraform-provider-avi/avi
avi/provider.go:211: Println call has possible formatting directive %v
FAIL	github.com/avinetworks/terraform-provider-avi/avi [build failed]
make: *** [test] Error 1

       I can't test the code.

       Any help is much appreciated.

**Comment by Rishabh-Baranwal** [comment]
hi Arun,
For me the build is passing on master. Could you please confirm/ try rebasing to master and build it ?

**Comment by arun2arunraj** [comment]
Thanks Rishabh for checking that out. I will try that from the branch and
let you know the results.

**Comment by arun2arunraj** [comment]
It is working Rishabh. Thanks for the needful.
