### ISSUE TITLE
Pool members not correctly updated

### ISSUE THREAD

**Issue by RiRa12621** [avinetworks/terraform-provider-avi#87]
The issue occurs when trying to update an existing pool.

**Scenario**:
A pool is existing, with three members in it.
Three more nodes of the same kind are spawned in the same openstack tenant.
That is done by increasing the count of that class from 3 to 6.
The three additional nodes should be added to the same pool.
AVI version: 18.1.3
Avi-terraform-provider: 17.2.9 

**Behaviour**:
The existing three nodes are removed from the pool.
The three new nodes are added to the pool
The difference in desired vs real state is not detected.

**Tfcode**:

avi.tf(relevant parts):

`resource "avi_server" "ingress" {
  count    = "${var.tectonic_worker_count}"
  ip       = "${module.tectonic.worker_addresses[count.index]}"
  hostname = "${module.tectonic.worker_addresses[count.index]}"
  port     = "32160"
  pool_ref = "${module.ingress_vip.pool_ref}"
}
`

infra.tf(relevant part):

` tectonic_worker_count                 = “6”`

**Trace output from terraform plan**:

`2018-11-02T11:43:08.926+0100 [DEBUG] plugin.terraform-provider-avi: 2018/11/02 11:43:08 [DEBUG] Instance Diff is nil in Diff()
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[0]
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalSequence
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalInterpolate
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalGetProvider
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalValidateResource
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalReadState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalDiff
2018-11-02T11:43:08.928+0100 [DEBUG] plugin.terraform-provider-avi: 2018/11/02 11:43:08 [DEBUG] Instance Diff is nil in Diff()
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[1]
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalSequence
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalInterpolate
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalGetProvider
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalValidateResource
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalReadState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalDiff
2018-11-02T11:43:08.930+0100 [DEBUG] plugin.terraform-provider-avi: 2018/11/02 11:43:08 [DEBUG] Instance Diff is nil in Diff()
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[4]
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalSequence
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalInterpolate
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalGetProvider
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalValidateResource
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalReadState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalDiff
2018-11-02T11:43:08.931+0100 [DEBUG] plugin.terraform-provider-avi: 2018/11/02 11:43:08 [DEBUG] Instance Diff is nil in Diff()
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[2]
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalSequence
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalInterpolate
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalGetProvider
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalValidateResource
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalReadState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalDiff
2018-11-02T11:43:08.932+0100 [DEBUG] plugin.terraform-provider-avi: 2018/11/02 11:43:08 [DEBUG] Instance Diff is nil in Diff()
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[3]
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalSequence
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalInterpolate
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalGetProvider
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalValidateResource
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalReadState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalDiff
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalCheckPreventDestroy
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteState
2018/11/02 11:43:08 [TRACE] root.k8s_infra: eval: *terraform.EvalWriteDiff
2018/11/02 11:43:08 [TRACE] [walkPlan] Exiting eval tree: module.k8s_infra.avi_server.ingress[5]
`

**Comment by grastogi23** [comment]
@RiRa12621 are you trying to create multiple vips or multiple servers. If you can use the latest provider then you can create backend pool servers using new avi_server resource


resource "avi_pool" "test-p2" {
  name= "pool-p2",
  //health_monitor_refs= ["${avi_healthmonitor.test_hm_1.id}"]
  tenant_ref= "${data.avi_tenant.default_tenant.id}"
  cloud_ref= "${data.avi_cloud.default_cloud.id}"
  application_persistence_profile_ref= "${avi_applicationpersistenceprofile.test_applicationpersistenceprofile.id}"
  fail_action= {
    type= "FAIL_ACTION_CLOSE_CONN"
  }
  ignore_servers= true
}

resource "avi_server" "test_server_p21" {
  ip = "10.90.64.111"
  port = "80"
  pool_ref = "${avi_pool.test-p2.id}"
  hostname = "foo"
}

**Comment by gitshrikant** [comment]
@RiRa12621 Hey Hi, 
Are you able to run your scripts with latest AVI provider (18.2.1)? Let me know if you are facing any difficulties. As mentioned above, you can add/create/delete pool servers form an existing pool using 'avi_server' resource.

**Comment by grastogi23** [comment]
We have fixed the issue with avi_server. Please check again and let us know if you see any issues.

**Comment by weargoggles** [comment]
fixed in #104
